### ISSUE TITLE
Support multiple versions/targets of `spack` with differing configs

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/spack_config#7]
Different versions of spack may require different versions/targets of `spack_config`. 

Either:
* Have multiple branches for each version of `spack`, or
* Have versioned configs within `main`

**Comment by harshula** [comment]
Should we have symmetry with the spack instance? e.g.
```
$ git branch -r | grep releases\/
  origin/releases/v0.10
  origin/releases/v0.11
  origin/releases/v0.12
  origin/releases/v0.13
  origin/releases/v0.14
  origin/releases/v0.15
  origin/releases/v0.16
  origin/releases/v0.17
  origin/releases/v0.18
  origin/releases/v0.19
  origin/releases/v0.20
  origin/releases/v0.21
```
i.e. Have a `v0.20`, `v0.21`, ... branches?

Or do we want transparency and have versioned config directories in `main` branch? I've been flip-flopping between these two options since last week.

**Comment by CodeGat** [comment]
I'm really not sure...I do like the idea of versioned config directories. Seems a bit simpler to maintain than having to modify each branch whenever something needs to be modified.

**Comment by harshula** [comment]
Fixed by PR https://github.com/ACCESS-NRI/spack_config/pull/10
